import "@radix-ui/themes/styles.css";
import './theme.config.css'
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Popover } from "radix-ui";
import Navbar from "../components/Narbar"
import SideMenu from "../components/SideMenu";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import { CartProvider } from "@/context/CartContext";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}><AuthProvider><Theme><Navbar/><main className="p-5"><CartProvider>{children}</CartProvider></main></Theme></AuthProvider></body>
    </html>
  );
}
